### PR TITLE
add link to Zulip chat

### PR DESCRIPTION
**Pull request by dimpase**

### CODE REVIEW

**Review by haraldschilly — APPROVED** [review]

**Comment by dimpase** [comment]
thanks. In particular as `"the freenode IRC network has been taken over by a narcissistic Trumpian wannabe Korean royalty bitcoins millionaire." `

**Comment by haraldschilly** [comment]
oh no, wow. in any case, I think this should be in the help dropdown menu, instead of IRC. I'll make a follow up.

**Comment by dimpase** [comment]
OK, thanks - I thought I did fix the dropout menu - but apparently not. You know better than me what to do here. As to IRC - the story was making headlines few days ago. freenode admins resigned en masse and set up https://libera.chat/

**Comment by haraldschilly** [comment]
wow. … and in case you're curious, each page is generated based on a template (to not repeat that part which is the same everywhere). https://github.com/sagemath/website/commit/068c54057329cfda3f8bf6508676e413ce8bb788

**Comment by dimpase** [comment]
I just pushed https://github.com/sagemath/website/commit/61d25dfd33c6bff3bdcc1ba1a2264ab2347a58e1 - a cosmetic change. Does it deploy automatically, or you need to push buttons?

**Comment by haraldschilly** [comment]
No, it doesn't deploy automatically.

**Pull request merged**
