### PR TITLE
Add the Computational Mathematics with SageMath website

### PR DESCRIPTION
**Pull request by embray**
The original hosting for this book's repository, and its website, gforge.inria.fr, is being permanently shut down in the coming days.

After some discussion on the mailing list for the book, we thought the best place to host the website might be the sage website itself (which already prominently advertises the book).  This is just a matter of adding a few html files and related image assets to the website, and updating some links.

I've added a complementary PR to the bibliography at sagemath/publications#126

### CODE REVIEW

**Review by haraldschilly — APPROVED** [review]

**Comment by haraldschilly** [comment]
Ok, I checked it and looks good. I also merged the publication PR and everything should be live shortly…

**Comment by embray** [comment]
@haraldschilly Thank you!

**Comment by embray** [comment]
Hmm, the only problem is if you go just to https://www.sagemath.org/sagebook/ it's a 404.  I hope having both index.en.html and index.fr.html would work with the .htaccess file, but maybe I'm missing something.  Or is the site not even hosted on Apache?  I guessed it was since I saw some other .htaccess files.

**Comment by haraldschilly** [comment]
@embray it's hosted on a CDN (fastly) via github pages. I have no idea what technology they use, but .htaccess files aren't supported.

Related to that I fixed the link in the publications entry to point to  a page and not just the directory. https://github.com/sagemath/publications/commit/3b3428e414fa204840e9913b5808c2a562893775

So, that's being taken care of.

Maybe a stub index.html page is a good fix? It could even redirect to a page, via such a http header tag.

**Pull request merged**
