### PR TITLE
contributors.xml: Add contributors G* from sage-changelogs

### PR DESCRIPTION
**Pull request by mkoeppe**
@kwankyu

### CODE REVIEW

**Comment by kwankyu** [comment]
There are 687 contributors in the changelogs missing in contributors.xml.

Are you adding all of them, manually, from A to Z?

My script can do it at once. Do you want me do that? I asked this before but you didn't answer. So I thought you were -1 in doing this...

**Comment by mkoeppe** [comment]
Sorry, I must have missed this! Yes, +1 for using your script to do it all!

**Comment by kwankyu** [comment]
All of 687 names of the changelog do not seem to appear in the current `contributors.xml`. This is strange to me. Is this reasonable?

**Comment by kwankyu** [comment]
Sorry I must be doing something wrong, obviously.

**Comment by mkoeppe** [comment]
My script `contributors-from-sage-changelogs.py` also gives this number of 687 missing names.

**Comment by kwankyu** [comment]
Right. There are much more names in the changelog than that. I was confused.

**Comment by kwankyu** [comment]
The script is not quite correct. See
```
python3 contributors-from-sage-changelogs.py | grep 'Bissey'
 name="Francois Bissey"/>
```
My new count is 655.

**Comment by mkoeppe** [comment]
Yes, my script makes no attempt to normalize names. I had planned to add the alternate spellings as `altnames` attributes

**Comment by kwankyu** [comment]
I made PR #350. 

This PR may be closed.

**Pull request closed without merging**
