### PR TITLE
Update link to SymPy website

### PR DESCRIPTION
**Pull request by gxyd**

### CODE REVIEW

**Comment by gxyd** [comment]
Fixes #88

**Comment by haraldschilly** [comment]
wow, didn't expect a PR. the state right now regarding that is a mess. so, if you change that, you also have to change the definition here: https://github.com/sagemath/website/blob/962c1cba8eddb7d447045ef149cfac24f1af0742/conf/packages.yaml#L410

caveat is, that this should actually be rendered via the jinja2 template engine based on that config file. so, only by also fixing the supposed source file to this, your change doesn't get lost.

I don't know, do you also want to fix the url there? I can also do it...

**Comment by gxyd** [comment]
I have fixed the link on the line you mentioned. I don't have much of website building knowledge.
> wow, didn't expect a PR.

I care about SymPy and creating a PR isn't a big deal. Thanks for being quite responsive to my PR.

**Comment by haraldschilly** [comment]
ok, LGTM and thank's again :-)

**Pull request merged**
