### PR TITLE
Add sitemaps

### PR DESCRIPTION
**Pull request by paulmasson**
I've created sitemaps appropriate to this website, if you want to use them. I omitted all of the redirects to documentation files, as well as several pages of no interest to readers, like the 404 redirect page and the Google identifications. If you merge the sitemaps, I'll submit them to Google Webmaster Tools.

### CODE REVIEW

**Comment by mrennekamp** [comment]
Did you manually generate these? If there "several pages of no interest to readers", how did you decide that? Eg. www.sagemath.org/version.html has no use to me; all it says is "7.4".

**Comment by paulmasson** [comment]
@mrennekamp I used the GitHub API to list all HTML and PDF files under the `src` directory. I can delete more uninteresting files if desired.

**Comment by mrennekamp** [comment]
@paulmasson Really, I have no problem with it. This and #102 fix problem #86, yes?

**Comment by paulmasson** [comment]
@mrennekamp the sitemaps in the documentation repository address #86, since that's where they should have gone initially and where I've been updating them. The sitemaps in this pull request are intended to help a bit with indexing www.sagemath.org as opposed to doc.sagemath.org.

**Comment by mrennekamp** [comment]
@paulmasson Okay. Thank you for making that clear - you did a one-two with removing doc.sagemath.org sitemaps to adding one for www.sagemath.org, which was confusing.

**Comment by haraldschilly** [comment]
merged it, shouldn't hurt. thank's!

**Pull request merged**
