### PR TITLE
scripts/geocode.py: Show GH user name, links to GH commit search

### PR DESCRIPTION
**Pull request by mkoeppe**

### CODE REVIEW

**Comment by kwankyu** [comment]
You can change the element class to `github`, if you do this 
```diff
--- a/src/res/sage.css
+++ b/src/res/sage.css
@@ -679,6 +679,8 @@ div.mdesc ul {
     padding: 3px 0 3px 1em;
     margin: 0;
 }
+
+.github,
 .trac {
     text-align: right;
     display: block;
```

**Comment by kwankyu** [comment]
I do not insist but prefer `"commits (github: {github})"`

**Comment by mkoeppe** [comment]
Thanks! I've made these changes

**Comment by kwankyu** [comment]
You didn’t change trac to github in setAttribute yet..

**Comment by kwankyu** [comment]
Sorry I should have mentioned that in the diff.

**Pull request merged**
