### PR TITLE
Create flat-file sitemaps

### PR DESCRIPTION
**Pull request by paulmasson**

### CODE REVIEW

**Comment by paulmasson** [comment]
Fixes #86

**Comment by haraldschilly** [comment]
merging it, and copying those files to the documentation repository, too

**Comment by haraldschilly** [comment]
ok, also here: https://github.com/sagemath/documentation/commit/10b5fefe3dbc06ce9afc8b80250dfd37ec068251

**Comment by haraldschilly** [comment]
ok, few hours ago, the webmaster tools still say "pending". the check said it's a valid file, so well, we have to wait until the crawler comes by :hourglass_flowing_sand:

**Pull request merged**
