### PR TITLE
Update mirror index page

### PR DESCRIPTION
**Pull request by mkoeppe**
@haraldschilly Is this the correct file to edit? It does not match http://files.sagemath.org/index.html exactly

### CODE REVIEW

**Comment by haraldschilly** [comment]
Hmm, I have to look through the ancient code of this mirror index script. It could very well be that the actual files on the mirror need to be modified and this is just a static copy to get started in case of complete disaster.

**Comment by haraldschilly** [comment]
I'm pretty busy the next few days. I'll see what changes you made and then copy/paste this onto the mirror page. So, it's on my radar!

**Comment by mkoeppe** [comment]
Great, thanks!

**Comment by mkoeppe** [comment]
Also http://files.sagemath.org/win/index.html should be updated: Perhaps with a README that 
- points to the Installation Guide
- Indicates the "Known Isuues with the Sage 9.3 Windows Installer" from https://github.com/sagemath/sage-windows/releases

**Comment by haraldschilly** [comment]
ok, I changed this. The page is different, hence I ported these changes in the same spirit. I don't know if it is now broken, because the files.sagemath.org webserver is yet again down.

Regarding your last comment, what's the installation guide? Is it this mysterious link: https://7896a56df78170d5bab0f306d1a7230986a4206a--sagemath-tobias.netlify.app/installation/index.html ? I set it to point there, just like it is done for the website itself.

**Comment by mkoeppe** [comment]
Thank you!

In http://files.sagemath.org/win/index.html there's a typo:  Isuues -> Issues

**Comment by mkoeppe** [comment]
> Regarding your last comment, what's the installation guide? Is it this mysterious link: https://7896a56df78170d5bab0f306d1a7230986a4206a--sagemath-tobias.netlify.app/installation/index.html ? I set it to point there, just like it is done for the website itself.

Thanks! This link works for now. We can replace it by a link to https://doc.sagemath.org/html/en/installation/index.html as soon as the 9.6 docs are available.

**Comment by haraldschilly** [comment]
@mkoeppe just FYI: I just updated doc.sagemath.org to version 9.6

**Comment by mkoeppe** [comment]
Thanks! I've sent you PR #262 to update the links

**Pull request merged**
