### PR TITLE
template PR for Catalina

### PR DESCRIPTION
**Pull request by kcrisman**
This is a template for adding some wording about people who have had difficulties regarding Catalina in binaries.

### CODE REVIEW

**Comment by haraldschilly** [comment]
hmm, I'm not sure what this is supposed to do. If it is merged, it will appear on the website, but there is no link ` <a href="">`.

**Comment by kcrisman** [comment]
> hmm, I'm not sure what this is supposed to do. If it is merged, it will
> appear on the website, but there is no link <a href="">.
>
>
See the sage-devel post regarding this:
https://groups.google.com/forum/#!topic/sage-devel/KuZXlKFHofI  It should
not be merged as it stands, for sure!    But it's possible that simply
linking to some instructions in the (currently empty) link would suffice.
Hopefully some recent Mac experts will be able to weigh in.

>

**Comment by kcrisman** [comment]
@haraldschilly I have updated with a better link and some more verbiage.  However, it's not quite ready to merge yet - I need to know where to find the code for the mirror pages like http://mirrors.mit.edu/sage/osx/index.html and http://mirrors.mit.edu/sage/osx/intel/index.html which I can't seem to find on the main website repo (or, at least doing a search for some of the words there didn't come up with anything).  Let me know, and then I can update all those and we will be good to go.

**Comment by kcrisman** [comment]
@haraldschilly ping - do you know where the mirror pages' code lives?

**Comment by haraldschilly** [comment]
> @haraldschilly ping - do you know where the mirror pages' code lives?

yes, sure, the pages are on the mirror itself based on a template. what again are you wondering about?

**Comment by kcrisman** [comment]
Right, I mean where is that template?   For e.g. http://mirrors.mit.edu/sage/osx/index.html and http://mirrors.mit.edu/sage/osx/intel/index.html which I cannot find exact wording of anywhere on this repo.  But maybe they are in a separate repo, like publications?

**Comment by haraldschilly** [comment]
Those index pages are derived from https://github.com/sagemath/website/blob/master/scripts/mirror-index-template.xml ... somewhere in the code are indexing scripts. I've not looked into this for 10 years or so. Hence please excuse that I'm not familiar with all the details. You can find text like "Not sure what to download" there. Is this your question?

Or maybe you mean the text in the middle? Can you tell me which text exactly you are looking for? There is also a file with extra notes, which lives on the [master mirror](http://files.sagemath.org/) and in `/home/files/files/osx/notes.txt`. The merger happens [here during indexing](https://github.com/sagemath/website/blob/b2bc63783ebd5ffb94e3fdfc5d41a3f54f53a9a1/scripts/mirror-index.py#L117).

**Comment by kcrisman** [comment]
> Hence please excuse that I'm not familiar with all the details. 

Very excused; the problem is just that it's not easy to find some of this.  E.g. the phrase "Choose your type of CPU (click on "About this Mac"): " or "to get Sage as a Mac OS X application that starts like most other Mac applications".

Is the source for files.sagemath.org somehow changeable via github?  The specific page you point to needs some reorganization, see e.g. #198

**Comment by haraldschilly** [comment]
No, it's not in git, it's a file just like the binaries that are served. The whole content is this:

```
<div style="margin: 0; margin-top:10px; padding: 0">
Choose your type of CPU (click on "About this Mac"):
<ul>
<li>Intel (i.e. most Macs less than five years old)</li>
<li>PowerPC (G4's, G5's)</li>
</ul> 
</div>
```

and well, I can upload changes there. More "reorganization" requires to work on the entire indexing system, which is higher challenge :-)

Maybe you could write something "nice" and "general" there, I'll add some "highlighting" (like a border or background, I don't know ...)  and in essence it links to a page in the wiki? Then, the page itself isn't cluttered and anyone can fine tune the wiki page.

**Comment by kcrisman** [comment]
Thank you very much for the fine-grained detail!  Wow, that is more complex than I was expecting.  I don't have time for that today, but probably later this week - and at least some of it is really necessary.
Is there a link where I can see those actual (raw) files?  One could literally never find `http://files.sagemath.org/osx/notes.txt` (or friends) by just following links, but one needs to be comprehensive about this.
I can think about the wiki side of things too, of course, that is a good idea for some things.  But for the people some of this is aimed at, the fewer clicks the better, by far.

-----

In the meantime I suggest checking out whether the _current_ pull request looks okay to you, and merging it post haste, if you agree.   There have been enough problems with OS X 10.15 that something should be on the download page, and should have been for some time.

**Comment by slel** [comment]
I guess this can be closed after #214 and #215.

**Pull request closed without merging**
