### PR TITLE
Developer map: Display Trac account name, improve search

### PR DESCRIPTION
**Pull request by mkoeppe**
Also adds an `altnames` attribute (comma-separated) and allows `trac` to be a comma-separated list @kwankyu

### CODE REVIEW

**Comment by kwankyu** [comment]
I didn't test, but you may need
```diff
--- a/scripts/geocode.py
+++ b/scripts/geocode.py
@@ -157,6 +157,7 @@ def writeToDevmap():
             tracQuery += f"&or&author=~{name}"
             tracQuery += f"&or&reviewer=~{name}"
         tracQuery += "&max=500&col=id&col=summary&col=author&col=status&col=priority&col=milestone&col=reviewer&order=priority"
+        tracQuery = tracQuery.replace(" ", "%20")
         a.setAttribute("href", tracQuery)
         a.setAttribute("class", "trac")
         if main_trac:
```
as names contain spaces.

**Comment by mkoeppe** [comment]
Yes, that's better, thanks.

**Comment by mkoeppe** [comment]
(I've tested with `make devmap` and then opening `templates/devs.html` in the browser)

**Review by kwankyu — APPROVED** [review]
LGTM.

**Comment by kwankyu** [comment]
I cannot approve this, perhaps because I don't have write access.

**Review by kwankyu — APPROVED** [review]

**Comment by mkoeppe** [comment]
I think this is something that we need to figure out in general for the github transition - how to configure reviews, project membership, and teams

**Comment by kwankyu** [comment]
Thanks, Harald!

**Pull request merged**
