### PR TITLE
adding 2 new-style svg logos

### PR DESCRIPTION
**Pull request by fchapoton**

### CODE REVIEW

**Comment by haraldschilly** [comment]
ok!

**Comment by fchapoton** [comment]
Thanks. I would like to use one of these (logo_sagemath.svg) at the top of http://doc.sagemath.org/

How to do that ?

**Comment by haraldschilly** [comment]
ok, but is there anything wrong with showing the sage logo graphic? why this change?

changes to the documentation page need to go into the project for it, not here for the website.

**Comment by haraldschilly** [comment]
or do you mean the individual pages of the sage documentation and not actually the http://doc.sagemath.org/ page itself? those are two different things.

**Comment by fchapoton** [comment]
I am meaning the very page "http://doc.sagemath.org/"
The idea is to use the new-style logos everywhere. I am doing this step by step.. This is now ok for trac and patchbot only.

**Comment by haraldschilly** [comment]
well,  I'm a bit against removing the graphic. I really like it :-)

The source for this page is this project: https://github.com/sagemath/documentation

**Comment by fchapoton** [comment]
I understand, but I am not very fond of this picture myself.

And the sagemath/documentation seems to contain many instances of "sage_logo_new_l_hc_edgy-nq8.png"..

**Comment by haraldschilly** [comment]
Well, I'm very fond of it and I think it's important to have a graphical element for recognition. 

I'm wondering if we should really discuss this here? Maybe a good compromise is to combine this svg logo here with the svg graphic which is part of this png file?

**Pull request merged**
