### PR TITLE
Remove src-old

### PR DESCRIPTION
**Pull request by mkoeppe**

### CODE REVIEW

**Comment by haraldschilly** [comment]
I don't agree with this, why do we want to get rid of that link pointing to older source versions? That's on the main file server and I'm sure there is occasional interest for an old version of Sage. Here is how it looks right now, going back to 2005 – and yes, those files exist on the server as well.

Screenshot from 2022-01-19 10-40-00

...

Screenshot from 2022-01-19 10-40-00

**Comment by kcrisman** [comment]
+1 though one could arguably de-emphasize it.

**Comment by mkoeppe** [comment]
I must have looked at this at a point in time when the server was down.

In any case, one of the redirects in `.htaccess` points to http://boxen.math.washington.edu/home/sagemath/www-files/src-old/ which is defunct

**Comment by haraldschilly** [comment]
ok, I had time to get back to this. I've removed all `.htaccess` files, they're unused bitrot stuff and removed one of these links to older sources, which aren't that important.

**Comment by mkoeppe** [comment]
Thanks!

**Pull request closed without merging**
