### PR TITLE
Drop extremely dated benchmark page

### PR DESCRIPTION
**Pull request by saraedum**
it would be nice to show benchmarks but until we have something pretty to show here, we should not show off a Sage from 2009.

### CODE REVIEW

**Comment by saraedum** [comment]
I did a `make` and `make open` locally and everything looked reasonable.

**Comment by saraedum** [comment]
@giacomopope, I cannot assign you as a reviewer here. I guess you do not have the right access to this repo. But please have a look anyway :)

**Comment by haraldschilly** [comment]
Is something like that in the documentation? Maybe it's worth linking to it.

**Review by haraldschilly — APPROVED** [review]
I would prefer to update the benchmarks instead of deleting it, but whatever :man_shrugging:

**Comment by saraedum** [comment]
@haraldschilly there are a few similarly dated things in the documentation but they don't tell a story. I am working on updating these and I'll create a PR here once there is something reasonable to show :)

Thanks for merging!

**Comment by haraldschilly** [comment]
:+1:

**Pull request merged**
