### PR TITLE
Download fixup

### PR DESCRIPTION
**Pull request by mkoeppe**
Fix up the page https://www.sagemath.org/download.html, which old release notes are pointing to.

Also replace the menu item pointing to the outdated sage-windows by a link to WSL installation.

### CODE REVIEW

**Comment by haraldschilly** [comment]
@dimpase please ping me once you finished reviewing in order to make these changes live

**Review by dimpase — APPROVED** [review]
lgtm

**Comment by dimpase** [comment]
> @dimpase please ping me once you finished reviewing in order to make these changes live

OK, @haraldschilly please go ahead

**Comment by haraldschilly** [comment]
🐾

**Pull request merged**
