### PR TITLE
Update contributor data

### PR DESCRIPTION
**Pull request by slel**
Minor update to contributor data.

### CODE REVIEW

**Comment by haraldschilly** [comment]
Thank's for the update, but as travis says, there is a unicode encoding problem. That needs to be fixed one way or another ...

**Comment by slel** [comment]
The offending unicode bit refers to a part that should be erased
by the last commit, so I'm puzzled here.
​

**Comment by slel** [comment]
Is there a way to squash the commits so the checks can pass?
Should I close this pull request and open a different one?

**Comment by haraldschilly** [comment]
Uhm, I don't think so and the characters are still there. Leave it as it is, and once I have a bit time to fix this, I'll do it. The best way forward is to debug the python code. You can also try to debug it, of course :-)

**Comment by haraldschilly** [comment]
I've merged this, but just FYI, here is the error I get and hence updating the website is broken. These travis CI checks are really helpful and they point out issues before they appear in the main master branch. You can clearly see that the accent signs aren't encoded and that's where it breaks. That's the same issue as was pointed out by travis.

```
Vincent Delecroix >>> LaBRI,+Université+de+Bordeaux,+Bordeaux,+France >>>
Traceback (most recent call last):
  File "scripts/geocode.py", line 241, in <module>
    addGeo(c.getAttribute("location"))
  File "scripts/geocode.py", line 202, in addGeo
    geo = getGeo(place)
  File "scripts/geocode.py", line 187, in getGeo
    geo = (urllib.urlopen(url)).read()
  File "/usr/lib/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/usr/lib/python2.7/urllib.py", line 185, in open
    fullurl = unwrap(toBytes(fullurl))
  File "/usr/lib/python2.7/urllib.py", line 1066, in toBytes
    " contains non-ASCII characters")
UnicodeError: URL u' https://maps.googleapis.com/maps/api/geocode/json?address=LaBRI,+Universit\xe9+de+Bordeaux,+Bordeaux,+France' contains non-ASCII characters
makefile:15: recipe for target 'templates/devs.html' failed
```

**Comment by haraldschilly** [comment]
ok, there were also problems with timeouts of geocoding all these locations -_-

patch for all this is here: https://github.com/sagemath/website/commit/c525dc758d6e045e81dcfbd47b30845893132a3d

**Comment by haraldschilly** [comment]
oh wow, latitude and longitude got mixed up. all new french people like you are bathing in the ocean now. :ocean:

**Pull request merged**
