### PR TITLE
Issue #133: homepage, implement a scrolling package list

### PR DESCRIPTION
**Pull request by vinklein**
Proposal for issue #133. 
Implement an horizontal scrolling package list with the
following features :
- The scrolling is stopped on mouse over the list to make
easier to click on an item.
- If javascript is allowed the list order is randomize,
otherwise the list is displayed in alphabetical order.

The scrolling mechanic use [CSS animation](https://www.w3schools.com/css/css3_animations.asp), and it can be not supported by (very) old browser version. I don't know what versions sagemath website officially support.

Implementation: 
As the modifications are very specific to the home page i have put them in the index.html file, let me know if you prefer them to be in specific .js and/or .css files.

### CODE REVIEW

**Comment by vinklein** [comment]
The list is not fully displayed on Microsoft Edge. I will fix that.

**Comment by vinklein** [comment]
Problems with Internet Explorer have been fixed.

**Comment by haraldschilly** [comment]
I've not looked at the result of that (and try to be neutral regarding a scrolling list), but what is IMHO a bad idea is to hardcode all the links to the packages. If something changes, someone has to go through all the files, and that's a maintenance nightmare.

There is a file defining all the packages at a central spot: https://github.com/sagemath/website/blob/master/conf/packages.yaml 

I suggest to use it via the templating system. I haven't looked at that in a long time, but I assume its data is exposed somehow. But ok, the components page isn't using it (no clue why) and the variable seems to have the name "packages". Maybe you have a bit of time to look into this.

**Comment by haraldschilly** [comment]
related to my last comment, I've changed the components links page to use the config file. Please have a look what's going on here: https://github.com/sagemath/website/blob/master/src/links-components.html

**Comment by vinklein** [comment]
> There is a file defining all the packages at a central spot: https://github.com/sagemath/website/blob/master/conf/packages.yaml

Thanks, i doesn't know that. I totally agree with you and will modify this branch accordingly.

**Comment by vinklein** [comment]
Just to be clear the branch has been updated. Now the reamining questions are "do we really want this ?" and if yes "is the current place of the current list is convenient or not ?".

**Comment by haraldschilly** [comment]
Well, obviously, nobody checks here this bugtracker. So, maybe something like that should go sage-devel?

What I find weird is the random ordering, but I get the point of being neutral.

Apart from that, technically a trailing comma in a list is fine in JS (also python). So, this looks easier to comprehend. (but it's just nitpicking)

```
pList= [
{% for spkg in spkgs %}
    '<a href="{{spkg.url}}">{{spkg.name}}</a>',
{% endfor %}
];
```

**Comment by haraldschilly** [comment]
FYI, I recorded a short screencast, which might help others to decide on that.

https://cocalc.com/share/b0d4fd8f-ea60-47cc-9af0-c1829dc0d2a9/sagemath.org-scrolling.webm?viewer=share

**Comment by vinklein** [comment]
For the trailing comma in javascript array it doesn't work consistently across browser  ([source](https://www.w3schools.com/Js/js_arrays.asp)). 

> IE 8 and earlier will fail.

Well you can argue that we don't support these old version (and css animation are not supported by IE8), but i am not sure if all others browser support the trailing coma.

**Comment by vinklein** [comment]
> FYI, I recorded a short screencast, which might help others to decide on that.

Suggestion :
Maybe it should show that the animation stop when mouse is over animation. Without that i will be  personally against this animation thing, because i think it's really annoying to have moving (and disappearing) clickable items.

**Comment by vinklein** [comment]
Link to the sage-devel discussion:
https://groups.google.com/forum/#!topic/sage-devel/H8FcZD90O0Y

**Pull request closed without merging**
