### PR TITLE
Update some links and data in library-press.html

### PR DESCRIPTION
**Pull request by slel**
Update http -> https, update urls for some links, update some data.

### CODE REVIEW

**Comment by haraldschilly** [comment]
I'm curious about the name change. I'm always using the current form, and it appears on many pages on the web. The github repository, https://zenodo.org/record/17093#.WqWRcXXwafY or http://www.lmfdb.org/knowledge/show/sage and even books like https://link.springer.com/chapter/10.1007%2F978-3-658-10453-5_3 (see abstract)

Was there anywhere a decision to change the name I'm not aware of?

**Comment by slel** [comment]
I was using the other one, but maybe I'm wrong. Reverted that.

**Comment by haraldschilly** [comment]
I don't know, I haven't seen that you made an additional change.

**Comment by haraldschilly** [comment]
merged it, and I'll make it live when I get around updating it

**Pull request merged**
