### PR TITLE
Add Samuel Lelièvre to contributors.xml

### PR DESCRIPTION
**Pull request by slel**
Add Samuel Lelièvre to contributors.xml

### CODE REVIEW

**Comment by haraldschilly** [comment]
well, travis-ci above complains. that's in the log:

```
Samuel Lelièvre >>> UNAM+Campus+Morelia,+Morelia,+Mexico >>>
Traceback (most recent call last):
  File "scripts/geocode.py", line 241, in <module>
    addGeo(c.getAttribute("location"))
  File "scripts/geocode.py", line 202, in addGeo
    geo = getGeo(place)
  File "scripts/geocode.py", line 192, in getGeo
    loc = geo["results"][0]["geometry"]["location"]
IndexError: list index out of range
make: *** [templates/devs.html] Error 1
```

so, that location is not known ...

**Comment by haraldschilly** [comment]
in case you don't want to play around with it, I can fix it later

**Comment by haraldschilly** [comment]
`19.651161` and `-101.223071`

**Comment by kcrisman** [comment]
@slel no way, UNAM-Morelia?  I had a very nice visit there many years ago ... cool.

**Pull request merged**
