### PR TITLE
Download link updates

### PR DESCRIPTION
**Pull request by mkoeppe**

### CODE REVIEW

**Comment by mkoeppe** [comment]
@haraldschilly Should the information in https://wiki.sagemath.org/DownloadAndInstallationGuide on bittorrent be merged into `scripts/mirror_manager.py`?

**Review by haraldschilly — APPROVED** [review]

**Comment by haraldschilly** [comment]
> @haraldschilly Should the information in https://wiki.sagemath.org/DownloadAndInstallationGuide on bittorrent be merged into `scripts/mirror_manager.py`?

Well, not sure what you mean, the part about opening up a compressed archive? That's something that applies to any download of Sage in a compressed archive. In the py file itself I found this part ... i.e. the main point is that the torrent client has to be able to load directly via the URLs.

→ https://github.com/sagemath/website/blob/master/scripts/mirror_manager.py#L430

**Comment by mkoeppe** [comment]
Sorry to be unclear. `scripts/mirror_manager.py` generates instructions that can be seen on this page https://www.sagemath.org/download.html in the section "Distributed / P2P". It is similar but not the same as the section titled "BitTorrent" on https://wiki.sagemath.org/DownloadAndInstallationGuide

I am suggesting to remove the section titled "BitTorrent" on https://wiki.sagemath.org/DownloadAndInstallationGuide
. And I would like to know if I can just remove it, or if some of the information there should be moved to `scripts/mirror_manager.py`

**Comment by haraldschilly** [comment]
Ok, I see, I transferred a bit of that page to this script and I the wiki page can be cleaned up. 4db091bdd061c039313aff0966abc32bf04653f8

**Pull request merged**
