### PR TITLE
new logo ?

### PR DESCRIPTION
**Pull request by fchapoton**
Just a proposal, only tiny change

### CODE REVIEW

**Comment by kcrisman** [comment]
I can see the old logo at https://www.sagemath.org/pix/sage_logo_new_l_hc_edgy-nq8.png but I couldn't find the new one - does the `+` sign function as it would in an email address or something?

**Comment by haraldschilly** [comment]
There is no file for the logo, that won't work. Besides that I'm very much against changing the logo. Is there a specific reason why we should do that? What's the problem with the current one?

**Comment by fchapoton** [comment]
By mistake, I have uploaded the files at the top level. They should be moved to pix..

https://github.com/sagemath/website/blob/master/logo_sagemath%2Bicon_oldstyle.png

**Comment by fchapoton** [comment]
I have moved the logos to the pix folder.

**Comment by fchapoton** [comment]
Here it is:



As you can see, this is just slightly refreshed, with sharper and more regular "sage" text.

Compare to the current one:

**Comment by haraldschilly** [comment]
so, I'm not sure how to proceed. should we just try it for a couple of days?

**Comment by fchapoton** [comment]
Maybe one could ask on sage-devel ? But I am a bit reluctant to ask such a futile question there..

**Comment by kcrisman** [comment]
> Maybe one could ask on sage-devel ? But I am a bit reluctant to ask such a
> futile question there..
>

I think that just a "yes/no" and majority wins would be fine - no bike
shedding allowed, yes or no only. (I don't think we have capacity nor need
for A/B testing, haha!)   I'll go on record as actually preferring the old
one, for what it's worth; I like the clearer demarcation between the
geometric logo and the word.

**Comment by williamstein** [comment]
I'm personally fine with us just making the switch.  Only if somebody complaints and requests a vote would we go that far.   I wouldn't want Sage to get so bureaucratic that every little change requires a vote, and hope voting should only be for situations where what to do is really unclear.   

It's good for the project to regularly have little refreshes like the logo.     The sagemath.org website iself -- though it's very functional and looks great -- also looks very "5 years old"... and it would be fantastic if somebody were to revamp and modernize it, and for that voting on everything would be really annoying...

Anyway, just my 2 cents.

**Comment by fchapoton** [comment]
By the way, some of the internationalized pictures in
https://wiki.sagemath.org/CorporateIdentity
need a language check, especially the russian one. I would like to have a chinese one two.

**Comment by kcrisman** [comment]
> I'm personally fine with us just making the switch. Only if somebody
> complains and requests a vote would we go that far. I wouldn't want Sage to
> get so bureaucratic that every little change requires a vote, and hope
> voting should only be for situations where what to do is really unclear.
>
>
And as long as all old and new logos are clearly available in some master
spot as before so people can use them for their own purposes for
"marketing", that is probably the most important thing.


> It's good for the project to regularly have little refreshes like the
> logo. The sagemath.org website iself -- though it's very functional and
> looks great -- also looks very "5 years old"... and it would be fantastic
> if somebody were to revamp and modernize it, and for that voting on
> everything would be really annoying...
>
>
> True.

**Pull request merged**
