### PR TITLE
Create CleanWebsiteDesign

### PR DESCRIPTION
**Pull request by nathvi**
Cleaning up the website with Mega Man... 
:)

### CODE REVIEW

**Comment by williamstein** [comment]
spam

**Comment by nathvi** [comment]
@williamstein, Why is this spam? I was just hoping to suggest some things to make the website look cleaner...

**Comment by kcrisman** [comment]
@nathvi - usually pull requests have very concrete suggestions that can be immediately merged.  

In this case, if there really are specific ideas from the video you linked to (a common spammer technique, so probably all were reluctant to view it) that would help clean up the website, feel free to open an *issue* with some of the ideas involved (be specific).  I can't see how an 80's video game is relevant, but maybe that's because I never played that one!  But certainly no one would dispute the website is not perfect, though thanks to Harald's work it is a lot better than before.

**Comment by haraldschilly** [comment]
The Sage website is actually quite complex, because of Sage's generality and its multipurpose aspects (information, support/documentation, development, teaching, publishing and -- of course -- online product distribution). Your patch just adds a pointless file in the `.idea/` subdirectory. That directory is for Jetbrain's PyCharm and would probably cripple it. That's why we regard this as spam, sorry :japanese_goblin:

**Pull request closed without merging**
