### PR TITLE
adding Mastodon social media account

### PR DESCRIPTION
**Pull request by dimpase**
I haven't implemented  "like" for it - not tried.

### CODE REVIEW

**Comment by dimpase** [comment]
PS. I'm setting up this account - ping me if you want access to it...

**Comment by dimpase** [comment]
AFAIK, Mastodon does not do the silly "like" account things - a meaningful action w.r.t. to an account is to subscribe.

**Review by haraldschilly — APPROVED** [review]

**Comment by haraldschilly** [comment]
Ok, let's see where this goes. I'm not planning to be active, but I registered and my application is under review.

**Comment by dimpase** [comment]
that's not deployed, right? I'd like to see if `<a rel="me" href="https://mathstodon.xyz/@sagemath">{{ sage }} Mastodon page</a>` gets the "green tick" of verified account.

**Comment by haraldschilly** [comment]
@dimpase no, not yet, I can ping you here if it is live

**Comment by haraldschilly** [comment]
@dimpase ok, deployed now. I don't know what you mean by such a "green tick", but the link is now here: https://www.sagemath.org/library-press.html

**Comment by dimpase** [comment]
by a green tick, I mean how URLs look on e.g. https://mathstodon.xyz/@dimpase

**Comment by dimpase** [comment]
I have working <a rel="me" href="[https://mathstodon.xyz/@dimpase](view-source:https://mathstodon.xyz/@dimpase)">Mastodon</a></li> on 

Verification

Mastodon says:
```
You can verify yourself as the owner of the links in your profile metadata. For that, the linked website must contain a link back to your Mastodon profile. The link back must have a rel="me" attribute. The text content of the link does not matter. 
```

so something seems to be blocking this authentication

**Comment by haraldschilly** [comment]
@dimpase I'm not familiar with any of that, but [this page](https://docs.joinmastodon.org/user/profile/#verification) says the profile has to link to a page, which in turn links back. I don't see a link to the sagemath website.

Also, I can add a "<link ... >" attribute to the header, then it doesn't matter to which page the profile links to.

**Comment by haraldschilly** [comment]
ok, this change https://github.com/sagemath/website/commit/e6a4f4708bfae008b4446501c42ae2a0135c6f10 is deployed. And besides that link on the profile, maybe it takes a while to scan these pages and update the database? I wouldn't be surprised if this verification does not happen in an instant.

**Comment by dimpase** [comment]
> I don't see a link to the sagemath website.

On `view-source:https://mathstodon.xyz/@sagemath` there is
`<link href='https://www.sagemath.org' rel='me' type='text/html'>`
(it's a part of "Profile Metadata")

**Comment by haraldschilly** [comment]
OK, got it. Well, earlier that rel="me" link was only on the library-press page, but now it is also in the header and on each page. In particular: `view-source:https://www.sagemath.org/` → ` <link href="https://mathstodon.xyz/@sagemath" rel="me" />`

So, with that, I think we can close this ticket and blame that server to either have a bug or it takes some time to recognize this. :man_shrugging:

**Comment by dimpase** [comment]
Oh, right, certainly I can imagine that the location of the link on the
website does matter, and should match URL at Mastodon

**Comment by dimpase** [comment]
OK, I fixed this by changing the `rel` URL on Mastodon side to `https://www.sagemath.org/index.html`.
All good now.

**Pull request merged**
