### PR TITLE
Add more country and flag tags in mirrors.yaml

### PR DESCRIPTION
**Pull request by slel**
Adding more country and flag tags, although those were maybe guessed
from the name or url?

By the way, is there documentation for the possible values of the flag tag?

### CODE REVIEW

**Comment by haraldschilly** [comment]
oh well, yandex is europe, right, but there is no need for any other changes you did. [here is the code](https://github.com/sagemath/website/blob/master/scripts/mirror_manager.py#L116), which derives the flag from the country, and if that's not set, then from URL itself.

**Comment by slel** [comment]
Okay, but it doesn't hurt to have the information there, right?
Also, where is it documented for example that one should write
`flag: gb` rather than `flag: uk`?

**Comment by haraldschilly** [comment]
there is nothing documented. The list of flags is just a list of images with their names. They're located right here: https://github.com/sagemath/website/tree/master/src/pix/flags

There isn't much magic going on beyond that

**Comment by slel** [comment]
> There is nothing documented. The list of flags is just a list of images
> with their names. They're located right here:
> https://github.com/sagemath/website/tree/master/src/pix/flags

Thanks -- turns out there's an info file `_info.txt` there with a bit of context:
https://github.com/sagemath/website/blob/master/src/pix/flags/_info.txt

**Pull request merged**
